name: CI
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@v1.2
        with:
          node-version: '16'
          source-folder: ./
          git-user: $SOME_USERNAME
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages
